### PR TITLE
refactor: added jest mock file

### PR DESCRIPTION
**Pull request by gorhom**
## Motivation

This PR will introduce a jest mock file for the library.

### CODE REVIEW

**Comment by MarceloPrado** [comment]
@gorhom would you consider exposing the mock file into the published build?

**Comment by vhakulinen** [comment]
~The mock is missing `forwardRef`~

Sorry, I was too eager to comment on this.

I had a problem where the provided mock wasn't happy to be put in `forwardRef`, but I got it working after upgrading to newer version.

**Comment by rafinhaa** [comment]
Any news?

**Comment by vhakulinen** [comment]
On what?

**Pull request merged**
