### PR TITLE
fix: prevent default backdrop from blocking ui behind

### LINKED ISSUE #242: [v3] BottomSheetScrollView and BottomSheetBackdrop blocking the entire app content
# Bug

When mounting the sheet, it seems that the BottomSheetBackdrop is capturing your clicks and you cannot interact with the app.

It seems to happen only on iOS.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1  |
| react-native                    | 0.63.4  |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0  |

## Steps To Reproduce

Clone https://github.com/ferrannp/bottom-sheet-playground.

1. Click `Open` button to open the sheet
2. If it works, refresh JS and try again (does not work 90% of the times)

Describe what you expected to happen:

1. To not block the app content

## Reproducible sample code

https://github.com/ferrannp/bottom-sheet-playground

### PR DESCRIPTION
**Pull request by gorhom**
close #242 

## Motivation

replacing `TouchableWithoutFeedback` with `TapGestureHandler` solves the issue

### CODE REVIEW

**Comment by hanno-ferrannegre** [comment]
@gorhom ~~I can confirm this works as expected~~ 👍.

Edit: It breaks any interaction when the sheet is open on Android. Everything was working on Android so maybe you just need to apply the changes for iOS?

**Comment by gorhom** [comment]
i will investigate it on Android later today, thanks for spotting this issue 😅

**Comment by gorhom** [comment]
hi @hanno-ferrannegre , i did test it on android, and seems fine 🧐

i used your repo https://github.com/ferrannp/bottom-sheet-playground

https://user-images.githubusercontent.com/4061838/106497232-10010c00-64be-11eb-939d-06684abd998a.mp4

**Comment by ferrannp** [comment]
So weird @gorhom, look what it does in my Pixel 4 (real device):

android

A part from the Open button problem (that is probably elevation thing), I cannot then interact with the sheet (close it by gesture) and tapping the backdrop does nothing either.

On the other hand, installing the `3.2.1` works well on Android 😅 .

By the way you don't seem to have latest version of the repo (with `react-navigation` bottom tabs).

**Comment by gorhom** [comment]
@ferrannp i did test it in a simulator and pixel-c device with latest `react-navigation` and `bottoms-tabs`  and it works fine , could you clear your metro cache and try again ?

**Comment by ferrannp** [comment]
Mmm @gorhom:

```
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#fix/backdrop-touchable-component
rm -rf android/app/build
yarn start --reset-cache
yarn android
```

Still getting the same. So strange... You sure you don't have another change locally/not pushed? Or I am doing something wrong 😅 .

**Comment by gorhom** [comment]
@ferrannp hmm , okay , will test it shortly

**Comment by gorhom** [comment]
hmm downgrading `react-native-safe-area-context` to `0.7.3` fix the issue 🧐,

i'll investigate it more

**Comment by gorhom** [comment]
hey @ferrannp , could you try the latest commit ... last one i promise 😅

**Comment by ferrannp** [comment]
@gorhom no problem, I can try as many times as necessary 😄 .

Unfortunately, I still get it broken on Android (like in the gif I posted) 😕 .

**Comment by gorhom** [comment]
ah yea, i notice in your repo that you did not integrate `react-native-gesture-handler` on android , please complete its setup and try again :)

**Comment by ferrannp** [comment]
JAAA, oh boy totally forgot about that. Too many projects 😅 .  It is definitely working. So let's release it! Thank you!!!

**Pull request merged**
