### PR TITLE
fix: unmounting modals with navigation

### LINKED ISSUE #292: null is not an object (evaluating 'sheetsQueueRef.current[sheetsQueueRef.current.length - 1].ref.current.minimize')
# Bug

I'm trying to use BottomSheetModal and it crashes with this error.
image

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc0   |
| react-native-gesture-handler    | 1.10.0   |
| typescript    | 4.1.5   |

## Steps To Reproduce

1. Add BottomSheetModalProvider to the root App component.
2. Use BottomSheetModal on some screen in the app.
3. Go to that screen and present/dismiss BottomSheetModal a couple of times, then go back to previous screen and return back to screen with BottomSheetModal and it crashes.

## Code

`const SNAP_POINTS = [260];`

```
<BottomSheetModal
        ref={bottomSheetModalRef}
        index={0}
        snapPoints={SNAP_POINTS}
        handleComponent={BottomSheetHandle}
        backdropComponent={BottomSheetBackdrop}
        backgroundComponent={BottomSheetBackground}
        onDismiss={onDismiss}
      >
...
      </BottomSheetModal>
```

### PR DESCRIPTION
**Pull request by gorhom**
Resolves #292 #299 

## Motivation

to provide better handling when unmounting modals due to navigation changes

## Installation

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#fix/unmounting-modals-with-navigation
```

### CODE REVIEW

**Comment by gorhom** [comment]
@chybisov & @ksitko could you test this pr, thanks :)

**Comment by ksitko** [comment]
@gorhom The pr resolves the crash :) 
I seem to be getting a state update on an unmounted component warning though:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

@chybisov Are you getting the same or is this just me?

**Comment by gorhom** [comment]
@ksitko thanks for testing it and reporting this warning, i'll look into it shortly

**Comment by gorhom** [comment]
@ksitko  i have pushed a commit that will prevent state update when modal is not mounted 👍

**Comment by ksitko** [comment]
@gorhom Nice! I can confirm that latest commit fixed the warning. I found a different problem. When not in dev mode I'm getting a crash on opening a bottom model sheet with a "TypeError Attempted to assign to readonly property" error message.

**Comment by gorhom** [comment]
@ksitko thanks for pointing this issue out, it was with the new release of `portal`, i have fixed this now on both repos.

would you mind testing the latest commit, thanks :)

**Comment by ksitko** [comment]
@gorhom Latest commit looks good. Thanks for the speedy fixes! :D

**Pull request merged**
