### PR TITLE
feat: added Reanimated v2 support

### PR DESCRIPTION
**Pull request by sa8ab**
This makes the library work with reanimated 2

### CODE REVIEW

**Comment by sa8ab** [comment]
I wonder if it will drop the usage for reanimated1 or not?

**Comment by gorhom** [comment]
hi @sa8ab  ! thanks for submitting this PR, i'll test it now

**Review by gorhom — DISMISSED** [review]
>I wonder if it will drop the usage for reanimated1 or not?

yeah, this broke usage with Reanimated v1. However here are the solution:

in `constants.ts`, change the import of easing to be
```ts
const { Easing: EasingV1, EasingNode: EasingV2 } = require('react-native-reanimated')
const Easing = EasingV2 || EasingV1
```

in `BottomSheet.tsx`

```ts
const { interpolate: interpolateV1, interpolateNode: interpolateV2 } = require('react-native-reanimated')
const interpolate = interpolateV2 || interpolateV1
```

**Comment by gorhom** [comment]
hi @sa8ab , would you be able to update this pr ? i could pick it up :)

**Comment by sa8ab** [comment]
Hey @gorhom sorry for my late delay, I'm glad it is in the new version.

**Comment by gorhom** [comment]
@sa8ab nah , no worries about it, thanks for the contribution :)

**Pull request merged**
