### PR TITLE
fix: stabilise animated callback node variables

### LINKED ISSUE #250: [v3] BottomSheetBackdrop flashes on mounting
# Bug

In some ocsasions (not sure if because of `react-navigation` or not), `BottomSheetBackdrop` flashes (black to transparent) the whole screen.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1  |
| react-native                    | 0.63.4  |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0  |

## Steps To Reproduce

Clone https://github.com/ferrannp/bottom-sheet-playground.

1. Open the app
2. She the flash
3. Reload JS
4. See the flash
5. Comment out `backdropComponent={BottomSheetBackdrop}`
6. Reload JS
7. You will not see the flash

Describe what you expected to happen:

1. `BottomSheetBackdrop` not to flash when mounting

## Reproducible sample code

https://github.com/ferrannp/bottom-sheet-playground

### PR DESCRIPTION
**Pull request by gorhom**
close #250 

## Motivation

with this pr, `animatedIndex` and `animatedPosition` won't be interpolated until the layout is calculated.

## Installation

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#fix/animated-variables-flickering-v3
```

### CODE REVIEW

**Comment by gorhom** [comment]
@ferrannp could you please test this pr :)

**Comment by ferrannp** [comment]
Hey @gorhom, mmm it seems that it is still happening. In the code I cannot share happens all the time. In the playground https://github.com/ferrannp/bottom-sheet-playground happens less but if you keep reloading JS, you can see it still happens. See:

refresh

In this gif, the first reload is ok, the second one has the flash. It is a bit random, sometimes flashes on mount, sometimes not, etc.

**Comment by ferrannp** [comment]
FYI @gorhom this still happens even with the https://github.com/gorhom/react-native-bottom-sheet/pull/246 fix.

**Comment by gorhom** [comment]
could you try again with , make sure you clean metro cache and install this pr again

**Comment by hanno-ferrannegre** [comment]
@gorhom still sometimes happening to me.

**Comment by ferrannp** [comment]
@gorhom still sometimes happening to me.

**Comment by gorhom** [comment]
@ferrannp hmm i can't reproduce it 😩 , i would suggest to merge this pr since it provide more a stable `animatedIndex` ?

**Comment by ferrannp** [comment]
Yeah let's try and release @gorhom. Then I will try again with real version and try to reproduce it again.

**Pull request merged**
