### PR TITLE
Make sure ref exists with optional changing 

### PR DESCRIPTION
**Pull request by jcgertig**
Thanks for merging the last one I have reduced the crashes a lot with that. Not sure of the exact reason this one does not exist but I missed it in my last pr. I can dismiss the error and everything is fine, the sheet is closed, with this one so the chaining will just resolve the issue.

### CODE REVIEW

**Comment by jcgertig** [comment]
@gorhom any update for this?

**Comment by jcgertig** [comment]
@gorhom please review this and get it in as soon as you can. It will resolve a crash we have in our app currently. Thanks

**Comment by pashapear** [comment]
@gorhom Any word on this update? Thanks

**Comment by jcgertig** [comment]
@gorhom bump

**Review by gorhom — APPROVED** [review]

**Comment by gorhom** [comment]
thanks @jcgertig

**Pull request merged**
