### PR TITLE
feat: add onDragStart onDragEnd gesture callbacks

### LINKED ISSUE #998: Pan Gesture event
# Feature Request

## Why it is needed

This might be a feature request, or perhaps it's already available. I am trying to respond to the pan gesture. Basically, when the sheet is panned larger/smaller, I want another item to shrink / expand.

I've looked at the `gestureEventsHandlersHook` prop and this hook with no luck:
https://github.com/gorhom/react-native-bottom-sheet/blob/e15965f18ca90a45a34f963e57df3eb83f22444b/src/hooks/useGestureEventsHandlersDefault.tsx#L23

Is there a way to do this atm?

## Possible implementation

Perhaps a `onPanStart` and `onPanEnd` event.

### Code sample

No idea

### PR DESCRIPTION
**Pull request by arekkubaczkowski**
Given the significant interest and numerous requests from the community for this feature, I'm excited to introduce it with this pull request. 

resolves #998, #1147

### CODE REVIEW

**Comment by arekkubaczkowski** [comment]
@gorhom I think it's also worth to add a callbacks that run on UI thread to react on the changes without unnecessary rerenders. However I need to think a bit about some intuitive API for that

**Comment by arekkubaczkowski** [comment]
Additionally I would also consider adding them to some hook so user can interact with it from any place.

**Comment by arekkubaczkowski** [comment]
@gorhom I would be really grateful for review

**Comment by jakubdrozdek** [comment]
Awesome! Can't wait to see it merged. We've been patching this manually for quite some time. Would be nice to see it in the library.

**Comment by AndreiTimofte96** [comment]
Hi @arekkubaczkowski. Do you know when this awesome feature will be merged & released ?

**Comment by arekkubaczkowski** [comment]
> Hi @arekkubaczkowski. Do you know when this awesome feature will be merged & released ? 

I have no idea, it seems like @gorhom is very busy.

**Comment by phillipkey** [comment]
@arekkubaczkowski - I am currently trying to tap into some functionality like this and I _believe_ @gorhom's intent is to use `gestureEventsHandlersHook` to provide callbacks for `handleOnStart`, `handleOnEnd`, `handleOnActive`. 

Am I missing the intent of this PR?

**Comment by arekkubaczkowski** [comment]
@phillipkey could you provide some example on how to properly use `gestureEventsHandlersHook` without defining redundant boilerplate? I am not sure if I am missing something but based on official example it require to provide the entire logic from scratch instead of adding custom logic on the top of existing one.

**Comment by arekkubaczkowski** [comment]
that's a shame it's been closed. Hopefully someone will reopen it.
cc @gorhom

**Comment by arbaaz-suggaa** [comment]
@arekkubaczkowski  any idea when this feature will be availabe to use?

**Pull request closed without merging**
