### PR TITLE
Add callback to interrupt the closing of the bottom sheet component

### PR DESCRIPTION
**Pull request by AlexanderEggers**
Please provide enough information so that others can review your pull request:

## Motivation

In certain cases we want to conditionally prevent the bottom sheet component from closing and show a warning modal to the user instead.

### CODE REVIEW

**Comment by AlexanderEggers** [comment]
This PR is still revelant..

**Comment by AlexanderEggers** [comment]
@gorhom When you have a moment, can you please review this PR?

**Comment by emmsdan** [comment]
@gorhom 
I think this PR is a relevant use case.
Found myself, having to folk and implement something similar

**Comment by gorhom** [comment]
Will look into this this weekend

**Comment by karimcambridge** [comment]
Related to https://github.com/gorhom/react-native-bottom-sheet/pull/1320?

**Comment by AlexanderEggers** [comment]
@gorhom Do you have any updates around this PR?

**Comment by AlexanderEggers** [comment]
@gorhom Any updates?

**Comment by AlexanderEggers** [comment]
This PR is still relevant

**Comment by AlexanderEggers** [comment]
@gorhom I made some minor fixes to the changes and updated the PR with the latest master. Any chance that we can get this one merged soon?

**Comment by AlexanderEggers** [comment]
@gorhom Any updates?

**Comment by AlexanderEggers** [comment]
This PR is still relevant.

**Comment by AlexanderEggers** [comment]
@gorhom When do you think we can have this PR finally merged?

**Comment by AlexanderEggers** [comment]
This PR is still relevant.

**Comment by dima-vantage** [comment]
@gorhom any updates?

**Comment by edwardanthony** [comment]
Any updates on this?

**Comment by gaedlld** [comment]
Need it too !!

**Pull request closed without merging**
