### PR TITLE
fix: updated initial position to screen height

### LINKED ISSUE #642: [v4] Initial index -1 not working on Android Only
# Bug

When using the `-1` index to make sure that the sheet is closed on the initial render, the sheet works fine on IOS but not on android. Instead on android, the sheet renders a small portion at the bottom of the screen, which blocks interaction with contents outside the sheet.

WhatsApp Image 2021-09-15 at 11 08 55 PM

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.3   |
| react-native                    | 0.63  |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

Nothing big here, a simple example. Just set the index to `-1`.

Describe what you expected to happen:

The sheet should be closed on initial render and only show when a button is pressed

## Reproducible sample code

The snack code with the issue

https://snack.expo.dev/@aimensasi/bottom-sheet-v4-reproducible-issue-template

### PR DESCRIPTION
**Pull request by gorhom**
Resolve #642 

## Motivation

Android with translucent status bar causes the window height to be smaller than the screen height, which led the sheet to be visible when it is closed.

## Installation

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#fix/642-updated-initial-position-to-screen-height
```

### CODE REVIEW

**Comment by gorhom** [comment]
@aimensasi @aditya-keri-betterhalf could you guys test this pr , thanks 👍

**Comment by aditya-keri-betterhalf** [comment]
@gorhom - Works perfectly now. Thanks for the quick fix.

When can we expect a newer version with this fix to be released ?

**Comment by gorhom** [comment]
thanks @aditya-keri-betterhalf for testing, it should be released soon

**Comment by aimensasi** [comment]
Thanks a lot, I just installed the latest release and the issue is resolved.

**Pull request merged**
