### PR TITLE
fix: updated modal unmounting handling

### LINKED ISSUE #323: [v2] null is not an object (evaluating 'sheetsQueueRef.current[sheetsQueueRef.current.length - 1].ref.current.minimize')
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Add BottomSheetModalProvider to the root App component.
2. Use BottomSheetModal on some screen in the app.
3. Go to that screen and present/dismiss BottomSheetModal a couple of times, then go back to previous screen and return back to screen with BottomSheetModal and it crashes.

Same as #292 

Describe what you expected to happen:

1. No crash

## Reproducible sample code

```js
<BottomSheetModal
  ref={ref}
  snapPoints={[500]}
  backgroundComponent={() => <View />}
  backdropComponent={BottomSheetBackdrop}
  handleComponent={() => <View />}
  index={0}
  onChange={() => {}}
  onDismiss={() => {}}
>
  // ...
</BottomSheetModal>
```

### PR DESCRIPTION
**Pull request by gorhom**
Fixes #323 

## Motivation

this implements the new `portal` v1 and improve unmount handling 

## Installation

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#fix/updated-modal-unmounting-handling
```

### CODE REVIEW

**Comment by gorhom** [comment]
@Yonom could you test this 👍

**Comment by gorhom** [comment]
@krakz999 could you test this pr :)

**Comment by eliasrenman** [comment]
Hi I was experiencing the issue mentioned in #323 and with this fix I seem to be unable to produce a crash as described in the issue.

I Hope this information helps somewhat 👍

**Comment by Yonom** [comment]
Also unable to reproduce the issue now 👍 

Thanks a lot!

**Pull request merged**
