### PR TITLE
fix(BottomSheetContainer): cannot add new property 'value'

### PR DESCRIPTION
**Pull request by MoritzCooks**
### Motivation

Currently the v4 faces the issue `cannot add new property 'value'` (have a look at https://github.com/gorhom/react-native-bottom-sheet/issues/1292 and https://github.com/gorhom/react-native-bottom-sheet/pull/1293)
Those were automatically closed without fixing the issue.

To fix that issue, `BottomSheetContainer.tsx` has to check if `containerOffset.value` is available.

### CODE REVIEW

**Comment by MoritzCooks** [comment]
One more try 😄 
You will not get rid of me @gorhom !

**Comment by MoritzCooks** [comment]
My two previous PRs got automatically closed:
- https://github.com/gorhom/react-native-bottom-sheet/pull/1650
- https://github.com/gorhom/react-native-bottom-sheet/pull/1758

Please have a look at it. It's just one line to prevent a potential undefined `containerOffset` which happens in some cases.

**Comment by gorhom** [comment]
thanks for your contribution ,, i apologise for merging late

**Comment by MoritzCooks** [comment]
> thanks for your contribution ,, i apologise for merging late

No worries 🙂

**Pull request merged**
