### PR TITLE
chore: introduce bare-fabric example

### PR DESCRIPTION
**Pull request by AndreiCalazans**
## Motivation

This includes a fabric enabled example that can be used to verify the library is properly working with Fabric. 

The example app doesn't fully work with Fabric due to:
1) The usage of `findNodeHandle`
2) react-navigation's Card component using `setNativeProps`
3) Reanimated's V3 RC crashing when using `useReanimatedRef`. 

I have a follow up PR where I remove `findNodeHandle` usage from this library to make it fully compatible with Fabric. 

cc @gorhom

### CODE REVIEW

**Comment by gorhom** [comment]
Thanks @AndreiCalazans for submitting this PR.

I don't think we need to have an example for Fabric, or at least a separate example. I will look into extracting the example into another repo in the feature.

**Comment by AndreiCalazans** [comment]
> Thanks @AndreiCalazans for submitting this PR.
> 
> 
> 
> I don't think we need to have an example for Fabric, or at least a separate example. I will look into extracting the example into another repo in the feature.
> 
> 

Sounds good. It made it easier for me to test both in parallel. The example apps are nicely setup, nice job by the way.

**Comment by only1chi** [comment]
Is there any plan to review and merge this PR? 
I think this PR gets bottom-sheet compliant with reanimated v3.

**Comment by tomekzaw** [comment]
> Reanimated's V3 RC crashing when using useReanimatedRef.

Hello! Could you please submit an issue in Reanimated repo so we can address this problem as soon as possible? Thanks in advance!

**Pull request closed without merging**
