### PR TITLE
feat: support new prop for BottomSheetBackdrop, "pressBehavior"

### PR DESCRIPTION
**Pull request by jsamr**
See #344 

**Remark 1**: I moved `usePressBehavior` hook to a separate file for ease of cherry-picking into v2.
**Remark 2**: ~~Could not launch example project because of a patch error. So I haven't tested yet... @gorhom  Ping me when you fix it upstream~~ (Edit: fixed upstream!)

### `pressBehavior="close"`

https://user-images.githubusercontent.com/3646758/112657902-a05e2c00-8e31-11eb-96b7-0147d701ebcd.mp4

### `pressBehavior="collapse"`

https://user-images.githubusercontent.com/3646758/112658118-db605f80-8e31-11eb-83d7-dad40b993c7e.mp4

### `pressBehavior={1}`

https://user-images.githubusercontent.com/3646758/112658183-ed420280-8e31-11eb-93c6-18b1571cc198.mp4

### `pressBehavior="none"`

https://user-images.githubusercontent.com/3646758/112658239-fd59e200-8e31-11eb-82fe-fc75e1acb023.mp4

### `pressBehavior="collapse"` and `closeOnPress={true}`

**Remark**: notice the warning against using both props in the LogBox.

https://user-images.githubusercontent.com/3646758/112658717-71948580-8e32-11eb-9506-65e0406323ed.mp4

@gorhom We could propose a picker in the example to select the desired `pressBehavior`; but I didn't notice this pattern in other examples... what do you think?

### CODE REVIEW

**Comment by gorhom** [comment]
thanks @jsamr for submitting this pr, i have fixed the `/v3` branch now, you could pull it and try again :)

**Comment by jsamr** [comment]
@gorhom Ready for review. I've updated the OP with captures of each behavior!

**Comment by jsamr** [comment]
@gorhom Glad it got merged! Are you going to backport thiss on v2 on your own or do you want a separate PR?

**Comment by gorhom** [comment]
@jsamr i will work on `v2` pr, as soon as I prepare a new release for `v3`

**Comment by nikhilgautam810** [comment]
Not working this Press Behavior
    "@gorhom/bottom-sheet": "^5.1.4",


import React, { forwardRef, useEffect, useMemo, useState } from 'react';
import { Keyboard, StyleSheet, Text } from 'react-native';
import responsive, { isTablet } from '../../utils/responsive';
import { colors } from '../../utils/theme';
import BottomSheet, { BottomSheetBackdrop, BottomSheetView } from '@gorhom/bottom-sheet';

const renderBackdrop = (props) => (
  <BottomSheetBackdrop
    {...props}
    appearsOnIndex={0}
    disappearsOnIndex={3}
    opacity={1} // Set transparency
    pressBehavior="collapse"
  />
);




const BottomSheetWrapper = forwardRef(({ children, height, backgroundColor }, ref) => {
  const snapPoints = useMemo(() => [height, '40%'], [height]);

  return (
    <BottomSheet
      ref={ref}
      snapPoints={snapPoints}
      index={-1}
      disappearsOnIndex={1}
      enablePanDownToClose
      enableDynamicSizing={false}
      backgroundStyle={{
        backgroundColor: backgroundColor || colors.light.SCREEN_BACKGROUND,
        borderTopLeftRadius: isTablet ? 25 : 20,
        borderTopRightRadius: isTablet ? 25 : 20,
      }}
      keyboardBehavior="extend"
      handleIndicatorStyle={{ backgroundColor: colors.light.LIGHT_GRAY, width: responsive.width(12) }}
      backdropComponent={renderBackdrop}
    >
      <BottomSheetView style={{ zIndex: 1, backgroundColor: backgroundColor || colors.light.SCREEN_BACKGROUND, }}>
        {children}
      </BottomSheetView>
    </BottomSheet>
  );
});

export default BottomSheetWrapper;

const styles = StyleSheet.create({
  contentContainer: {
    backgroundColor: 'red'
  },
});

**Pull request merged**
