### PR TITLE
feat: add @shopify/flash-list support

### PR DESCRIPTION
**Pull request by MaxAst**
## Motivation

Shopify released [FlashList](https://shopify.github.io/flash-list/docs/usage) last year - a drop-in replacement for `FlatList` resulting in much better performance & UX. It would be great to be able to use it as part of `react-native-bottom-sheet`

### CODE REVIEW

**Comment by Darren120** [comment]
any idea when this will be merged? if not, is there a active fork?

**Comment by MaxAst** [comment]
I'd much rather have this get reviewed and merged, than maintain an active fork. @gorhom have you been able to have a look?

**Comment by bryanprimus** [comment]
I believe gorhom already implemented this, but it was for sponsors only.

https://twitter.com/gorhom/status/1546256656639614977?s=61&t=tmfaXBiWdovAjFWkmItV2A 

@gorhom  can we have this natively in version 5?

**Comment by ilyadynin** [comment]
Any updates on this? I would like to use BottomSheetFlashList, because my snapPoint is at 100% and when not using BottomSheetFlatList, but a standard FlatList or FlashList, when it is at the top and I drag it down to close the modal, it does not work but with BottomSheetFlatList it works really good.
 
But I'd still like to use FlatList

**Comment by Masoodt** [comment]
<FlashList
      contentContainerStyle={{ backgroundColor: theme.background.val }}
      data={memoData}
      keyExtractor={(item) => item._id}
      renderItem={renderItem}
      estimatedItemSize={320}
      //@ts-ignore
      renderScrollComponent={BottomSheetScrollView}
    />

**Comment by alexandrius** [comment]
@Masoodt @gorhom  rn
cover4_new_1200x768

**Comment by ronickg** [comment]
https://github.com/discord/react-native-bottom-sheet/pull/10 found this on discords fork might be interesting to also get it into the main repo.

**Comment by bryanprimus** [comment]
> <FlashList contentContainerStyle={{ backgroundColor: theme.background.val }} data={memoData} keyExtractor={(item) => item._id} renderItem={renderItem} estimatedItemSize={320} //@ts-ignore renderScrollComponent={BottomSheetScrollView} />

not sure why but this workaround is buggy


https://github.com/gorhom/react-native-bottom-sheet/assets/46083126/6f73ea7a-56e3-4410-a598-353e86f50b40

**Comment by altmshfkgudtjr** [comment]
> > <FlashList contentContainerStyle={{ backgroundColor: theme.background.val }} data={memoData} keyExtractor={(item) => item._id} renderItem={renderItem} estimatedItemSize={320} //@ts-ignore renderScrollComponent={BottomSheetScrollView} />
> 
> not sure why but this workaround is buggy
> 
>  Screen.Recording.2023-09-01.at.15.49.02.mov

I also have the same issue. Is there really no way to solve this problem?

**Pull request closed without merging**
