### PR TITLE
feat: add web support and example

### PR DESCRIPTION
**Pull request by axeldelafosse**
## Motivation

As discussed in this thread https://github.com/gorhom/react-native-bottom-sheet/discussions/427#discussioncomment-781252, this PR adds web support using `react-native-web` with Expo Web and Next.js.

## Note

We need to transpile `@gorhom/bottom-sheet` using `next-transpile-modules` so we are now using a local dependency to load the package.

You need to run `yarn build` in the root folder before running `yarn install` in the example folder. We could improve this by using a monorepo.

## Limitation

This is just using [this gist](https://gist.github.com/gorhom/9cd6155e8469c61d2ae9a815fcc83d2e) instead of  the `ShowcaseApp`. I'll add that later!

## Web support 🎉

We can now close this:
https://github.com/gorhom/react-native-bottom-sheet/issues/445
https://github.com/gorhom/react-native-bottom-sheet/issues/434
https://github.com/gorhom/react-native-bottom-sheet/issues/11

and this:
https://github.com/gorhom/react-native-bottom-sheet/pull/357
https://github.com/gorhom/react-native-bottom-sheet/pull/14

### CODE REVIEW

**Comment by gorhom** [comment]
hi @axeldelafosse , i cloned the project locally and when i try to run it i got 

```
index.tsx?8abf:359 Uncaught     at Function.values (<anonymous>)
    at useDerivedValue (webpack-internal:///./node_modules/react-native-reanimated/lib/reanimated2/Hooks.js:662:23)
    at Object.BottomSheet [as render] (webpack-internal:///./node_modules/@gorhom/bottom-sheet/lib/commonjs/components/bottomSheet/BottomSheet.js:1:6736)
    at ReactDOMServerRenderer.render (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function._callee$ (webpack-internal:///./node_modules/@expo/next-adapter/document.js:66:20)
    at tryCatch (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)
    at new Promise (<anonymous>)
    at Function.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at Function.getInitialProps (webpack-internal:///./node_modules/@expo/next-adapter/document.js:50:27)
    at loadGetInitialProps (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/next/dist/next-server/server/render.js:54:1145)
    at async (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/next/dist/next-server/server/next-server.js:112:97)
    at async (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/next/dist/next-server/server/next-server.js:105:142)
    at async DevServer.renderToHTMLWithComponents (file:///Users/gorhom/Desktop/oss/react-native-bottom-sheet-v3/example/node_modules/next/dist/next-server/server/next-server.js:137:387)
```

**Comment by axeldelafosse** [comment]
Weird. Do you want to jump on a call so I can help you debug this? You can send me an email at axel@expo.io

@nandorojo do you have the same error or is this working for you?

**Comment by nandorojo** [comment]
Can you try installing next-transpile-modules and adding `@gorhom/bottom-sheet`?

I can try this when I'm at a computer too

**Comment by nandorojo** [comment]
Oh sorry you did that already. I'll take another look.

**Comment by gorhom** [comment]
@axeldelafosse i have emailed you 👍

just more info about the issue, I removed the modal and just tried to use static `BottomSheet` and the first time it works but once i update the code base it throws the exception.

**Comment by nandorojo** [comment]
I'm traveling today but will try to look when I can. One issue I can see is that the expo next adapter is in dev dependencies.

**Comment by axeldelafosse** [comment]
Following up on this: you can replicate the bug by using `BottomSheet` without the `Modal`. This is weird because it's working correctly on another app.

> expo next adapter is in dev dependencies

This should not be a problem.

Any other ideas?

**Comment by nandorojo** [comment]
I think it could be a good move to shift this example into a standalone Next.js one. There are some merge conflicts now, but I can take a look at that

**Comment by axeldelafosse** [comment]
Yeah! Sorry I got caught up in other stuff. I'll send a new PR tomorrow. Happy Sunday :)

**Comment by axeldelafosse** [comment]
Hey guys! I moved this example into a fresh Expo + Next.js monorepo: https://github.com/axeldelafosse/bottom-sheet-example

**Pull request closed without merging**
