### PR TITLE
Fix: onClose loop

### PR DESCRIPTION
**Pull request by chreck**
There is already an issue about the looping of triggering onClose https://github.com/gorhom/react-native-bottom-sheet/issues/862

## Motivation

Calling `expand()` and closing the bottom sheet by slide it down triggers `onClose` in a loop https://github.com/gorhom/react-native-bottom-sheet/blob/0010008906154f9a545f89d5826ea7af48336610/src/components/bottomSheet/BottomSheet.tsx#L1517

### CODE REVIEW

**Comment by chreck** [comment]
I added aslo a fix for the situation when the user pulls down but releases finger after half of screen. It now sets animatedIndex to -1 manually.

**Comment by gorhom** [comment]
thanks @chreck for submitting this pr, i tried to repro the issue on my side , but i couldn't :(

would you please provide a minimal repro sample code ?

**Comment by chreck** [comment]
I commit an example with react native screens. It raises the onClose event, without my changes it did not. 
image

**Comment by Cleversou1983** [comment]
I'm facing the same issue

**Pull request closed without merging**
