### PR TITLE
fix: improve modal dismissing

### LINKED ISSUE #343: Cannot reopen modal
# Bug

When we have 2 bottom sheet modals in replace-mode, and you try to close both at the same time.
The first modal cannot be reopened.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.3   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Implement 2 bottom sheet modal
 - `modal1` must open `modal2`
 - The action on `modal2` is to close both `modal1` and `modal2`
2. Open `modal1`
3. Open `modal2`
4. Close both `modal1` and `modal2` from `modal2`
5. Try to open `modal1` (cannot be opened).

Describe what you expected to happen:

1. `modal1` should open

## Reproducible sample code

```jsx
import React, { useRef } from 'react';
import { TouchableOpacity, Text } from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';

const snap_points = ['20%'];

function MyComp() {
  const bottom_sheet_modal1_ref = useRef(null);
  const bottom_sheet_modal2_ref = useRef(null);

  const open_modal1 = () => {
    bottom_sheet_modal1_ref.current.present();
  };

  const open_modal2 = () => {
    bottom_sheet_modal2_ref.current.present();
  };

  const close_both_modals = () => {
    bottom_sheet_modal2_ref.current.dismiss();
    bottom_sheet_modal1_ref.current.dismiss();
  };

  return (
    <>
        <TouchableOpacity onPress={open_modal1}><Text>Open modal1</Text></TouchableOpacity>
        <BottomSheetModal ref={bottom_sheet_modal1_ref} snapPoints={snap_points}>
          <TouchableOpacity onPress={open_modal2}><Text>Open modal2</Text></TouchableOpacity>
        </BottomSheetModal>
        <BottomSheetModal ref={bottom_sheet_modal2_ref} snapPoints={snap_points}>
          <TouchableOpacity onPress={close_both_modals}><Text>Close both modal</Text></TouchableOpacity>
        </BottomSheetModal>
    </>
  );
}
```

- Click on `Open modal1`
- Then, click on `Open modal2`
- Then, click on `Close both modal`
- Then, click on `Open modal1` nothing happen

**NOTE: It's working if we inverse the closing order inside `close_both_modals` by:**
```js
  const close_both_modals = () => {
    bottom_sheet_modal1_ref.current.dismiss();
    bottom_sheet_modal2_ref.current.dismiss();
  };
```

### PR DESCRIPTION
**Pull request by gorhom**
Closes #343 

## Motivation

- improve modal dismissing
- fix crash when trying to find node when modal is umounted

## Installation

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#fix/improve-modal-dismiss
```

### CODE REVIEW

**Comment by gorhom** [comment]
@Dallas62 could you try this pr :)

**Comment by Dallas62** [comment]
Hi @gorhom 

Trying with the following code:

```jsx
import React, { useRef } from 'react';
import { TouchableOpacity, Text } from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';

const snap_points = ['20%'];

function MyComp() {
  const bottom_sheet_modal1_ref = useRef(null);
  const bottom_sheet_modal2_ref = useRef(null);

  const open_modal1 = () => {
    bottom_sheet_modal1_ref.current.present();
  };

  const open_modal2 = () => {
    bottom_sheet_modal2_ref.current.present();
  };

  const close_both_modals = () => {
    bottom_sheet_modal2_ref.current.dismiss();
    bottom_sheet_modal1_ref.current.dismiss();
  };

  return (
    <>
        <TouchableOpacity onPress={open_modal1}><Text>Open modal1</Text></TouchableOpacity>
        <BottomSheetModal ref={bottom_sheet_modal1_ref} snapPoints={snap_points}>
          <TouchableOpacity onPress={open_modal2}><Text>Open modal2</Text></TouchableOpacity>
        </BottomSheetModal>
        <BottomSheetModal ref={bottom_sheet_modal2_ref} snapPoints={snap_points}>
          <TouchableOpacity onPress={close_both_modals}><Text>Close both modal</Text></TouchableOpacity>
        </BottomSheetModal>
    </>
  );
}
```

It's working, **but** when i reorder the `close_both_modals`:

```js
  const close_both_modals = () => {
    bottom_sheet_modal1_ref.current.dismiss();
    bottom_sheet_modal2_ref.current.dismiss();
  };
```

I got:

```
 TypeError: null is not an object (evaluating '_sheetsQueue[_sheetsQueue.length - 2].ref.current.restore')
```

**Comment by gorhom** [comment]
hmm i am testing it here , and it works just fine.

try to clean install and clear metro cache

**Comment by Dallas62** [comment]
Restarting bundler made it works 😉 
Also working with my small use.

Didn't test more cases.

**Pull request merged**
