### PR TITLE
enable web support

### PR DESCRIPTION
**Pull request by zhigang1992**
### How to use this project with expo / react native web expo

By default, metro will transpile all `node_module` dependencies, but not webpack.

We need babel to transpile our Reanimated2 code.

To do so with Expo.

```javascript
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: [
          '@gorhom/bottom-sheet',
        ],
      },
    },
    argv,
  );
}
```

### CODE REVIEW

**Comment by zhigang1992** [comment]
After a day more detail usage, there seems to be some bug with the way we are using reanimated2.

For starter, without any modification, BottomSheetModal works, but not BottomSheet.

BottomSheet does show up when 

```diff
diff --git a/node_modules/@gorhom/bottom-sheet/lib/module/components/bottomSheet/BottomSheet.js b/node_modules/@gorhom/bottom-sheet/lib/module/components/bottomSheet/BottomSheet.js
index 9389339..7a91fdd 100644
--- a/node_modules/@gorhom/bottom-sheet/lib/module/components/bottomSheet/BottomSheet.js
+++ b/node_modules/@gorhom/bottom-sheet/lib/module/components/bottomSheet/BottomSheet.js
@@ -287,7 +287,7 @@ const BottomSheetComponent = /*#__PURE__*/forwardRef((props, ref) => {
 
   const containerAnimatedStyle = useAnimatedStyle(() => {
     return {
-      opacity: isLayoutCalculated ? 1 : 0,
+      opacity: 1,
       transform: [{
         translateY: isLayoutCalculated ? animatedPosition.value : safeContainerHeight
       }]
```

even when `isLayoutCalculated` is true, as soon as gesture get started, opacity become 0.

maybe we need to change `isLayoutCalculated` into a sharedValue?

I haven't look more into it at the moment.

cc @gorhom

**Comment by StampixSMO** [comment]
How would this work in a bare RN project?

**Comment by likeSo** [comment]
Hi, does this library support expo web now? I already configured `webpack.config.js` but when i ran `expo build:web` i got this error:
```sheet
./node_modules/@gorhom/bottom-sheet/lib/module/components/touchables/index.js
Cannot find module: './Touchables'. Make sure this package is installed.

You can install this package by running: yarn add ./Touchables.
Error: ./node_modules/@gorhom/bottom-sheet/lib/module/components/touchables/index.js
Cannot find module: './Touchables'. Make sure this package is installed.

```

How can i use this library on web?

**Comment by zhigang1992** [comment]
@likeSo yeah, you need the changes in this PR.

This library only has has Touchable.ios.js and Touchable.android.js so the web won't find anything.

But even after it compile on the web, don't get your hope too high, it still has other issues.

We endup just building our own bottom sheets.

**Comment by likeSo** [comment]
@zhigang1992 Thank you, so What's the progress about this PR? Will it be merged into v4?

**Comment by likeSo** [comment]
@zhigang1992 Thank you, so what's the progress about this PR? Will be merged into v4?
It's difficult to find a perfect library... Or do you have any suggestion? Haha

**Comment by zhigang1992** [comment]
@likeSo we eventually wrote our own bottom sheet with reanimated 2, worked out pretty well, even for web.

I'm no longer working on this PR.

Will close it out for now.

**Comment by waltermvp** [comment]
@zhigang1992 did you guys open source it?

**Comment by jeanniton-mnr** [comment]
> @likeSo we eventually wrote our own bottom sheet with reanimated 2, worked out pretty well, even for web.
> 
> I'm no longer working on this PR.
> 
> Will close it out for now.

Would you share / open source it?

**Comment by zhigang1992** [comment]
@waltermvp @jeanniton-mnr 

https://gist.github.com/zhigang1992/f358d99c8a406859b223470cc5a29ffe

we don't have the time / effect to maintain this outside of our own usecases.

But the basic idea is that we have two gestures, one to go full height, one to dismiss.

Instead of dealing with ScrollView's gesture simultaneously,

* we disable scroll when not full screen
* disable dismiss gesture when scroll view has scrolled.

It has its pros and cons but it works pretty well for us.

**Comment by jeanniton-mnr** [comment]
> 

Thank you @waltermvp @

> @waltermvp @jeanniton-mnr
> 
> https://gist.github.com/zhigang1992/f358d99c8a406859b223470cc5a29ffe
> 
> we don't have the time / effect to maintain this outside of our own usecases.
> 
> But the basic idea is that we have two gestures, one to go full height, one to dismiss.
> 
> Instead of dealing with ScrollView's gesture simultaneously,
> 
> * we disable scroll when not full screen
> * disable dismiss gesture when scroll view has scrolled.
> 
> It has its pros and cons but it works pretty well for us.   


I have tried to use your implementation.

However, I am not having it working. The console log `Cannot read properties of null (reading 'pan')`

Would you provide a working example/code?

Thank you!



PS: Below is my code, if this can help:    

```

import {
  Spacer,
  Text
} from '@components/1-atoms';

import {
  FullPage as Template
} from '@components/4-templates';

import Kontroler from '@assets/kontroler';
import Illustration from '@assets/email-illustration';

import {
  Button, Info, Input,
} from '@components/2-molecules';

import { Modal } from 'react-native';
import styled from '@emotion/native';


import Mail from '@assets/icons/mail';

import React, {  FC, useMemo, useRef, useState } from 'react';

/* 
import BottomSheet, {BottomSheetView} from '@gorhom/bottom-sheet';

const _BottomSheetView = styled(BottomSheetView)`
  height: 220px;
  align-items: center;
`;
 */


import {
  BottomSheet,
} from '@components/1-atoms';
import {BottomSheetView} from '@gorhom/bottom-sheet';
import { Props } from '@components/1-atoms/Text';


const _BottomSheetView = styled.View`
  height: 220px;
  align-items: center;
`;


const EmailLogin: FC<Props> = ({ ...props }) => {

  // hooks
  const snapPoints = useMemo(() => ['25%', '50%', '90%'], []);

  return (
    <Template title={"Login"}>

      <Spacer h={1} /> <Kontroler />
      <Spacer h={2} /> <Illustration /> <Spacer h={3} />

      <Text xlarge color="#FFF">Simplify your business</Text>
      <Spacer h={1} />
      <Text small color="#FFF">Create, manage and report under single app.</Text>

      <Modal animationType="none" transparent={true} visible={true} >

          <BottomSheet>
              <_BottomSheetView>
                <Text large color="#000">Provide email to continue</Text>
                <Spacer h={1} />

                <Input left={<Mail />} />

                <Button>VERIFY</Button>

                <Info>
                  You will need  to verify your email with an OTP that  we will send you shortly after.
                </Info>

                <Button bg={"transparent"}>TERMS OF USE</Button>

              </_BottomSheetView>
          </BottomSheet>
         
      </Modal>

    </Template>
  );
};
```

**Pull request closed without merging**
